openapi: 3.0.2
info:
  title: 'FSTR OpenAPI Specification'
  version: '0.0.1'
servers:
  - url: http://127.0.0.1:8000
tags:
  - name: users
    description: registered users
  - name: coordinates
    description: coordinates of pereval
  - name: pereval
    description: pereval main info
  - name: areas
    description: areas info
  - name: images
    description: images of pereval
  - name: pereval_images
    description: bound images with pereval by id
  - name: spr_activities_types
    description: types of movement

