openapi: 3.0.2
info:
  title: 'FSTR OpenAPI Specification'
  version: '0.0.1'
servers:
  - url: http://127.0.0.1:8000/
tags:
  - name: users
    description: all users
  - name: coordinates
    description: coordinates of pereval
  - name: pereval
    description: pereval main info
  - name: areas
    description: areas info
  - name: images
    description: images of pereval
  - name: pereval_images
    description: bound images with pereval by id
  - name: spr_activities_types
    description: types of movement
paths:
  /users:
    get:
      summary: Method to get list of all Users
      tags:
        - users
      operationId: listUsers
      description: List all registered users
      responses:
        '200':
          description: Success answer with list of Users
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Users'
        'default':
          description: All other events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Method to create User
      tags:
        - users
      operationId: createUser
      description: Create user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '201':
          description: New User has been successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        'default':
          description: All other events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /coords:
    get:
      summary: Method to get coordinates of pereval
      tags:
        - coordinates
      operationId: listCoordinates
      description: List coordinates for all perevals
      responses:
        '200':
          description: Success answer with coordinates to pereval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coords'
        'default':
          description: All other events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Method to add coordinates of pereval
      tags:
        - coordinates
      operationId: addCoordinates
      description: Add pereval coordinates
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Coord"
      responses:
        '201':
          description: New coordinated have been successfully added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Coord'
        'default':
          description: All other events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /perevaladded:
    get:
      summary: Method to get main info about of pereval
      tags:
        - pereval
      operationId: listPerevals
      description: List of all perevals
      responses:
        '200':
          description: Success answer with perevals
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Perevals'
        'default':
          description: All other events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Method to add main info about of pereval
      tags:
        - pereval
      operationId: addPereval
      description: Add pereval main info
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pereval"
      responses:
        '201':
          description: New pereval has been added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pereval'
        'default':
          description: All other events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      required:
        - code
        - name
      properties:
        code:
          type: integer
        message:
          type: string
    User:
      type: object
      properties:
        email:
          type: string
          example: Alex@example.com
        phone:
          type: sting
          example: '+79131234567'
        name:
          type: string
          example: Alex
    Users:
      type: array
      items:
        $ref: "#/components/schemas/User"
    Coord:
      type: object
      properties:
        latitude:
          type: number
          format: float
          example: 45.3842
        longitude:
          type: number
          format: float
          example: 7.1525
        height:
          type: integer
          example: 1200
    Coords:
      type: array
      items:
        $ref: "#/components/schemas/Coord"
    Pereval:
      type: object
      properties:
        user_id:
          type: integer
          example: 1
        beautyTitle:
          type: string
          example: 'пер. '
        title:
          type: string
          example: 'Пхия'
        other_titles:
          type: string
          example: 'Триев'
        level:
          type: string
          enum:
            - winter
            - spring
            - summer
            - autumn
          default: summer
        connect:
          type: string
          example: "nothing"
          default: "nothing"
        date_added:
          type: string
          example: "2021-09-22 13:18:13"
        add_first_time:
          type: string
          example: "2020-09-22 13:18:13"
        coord_id:
          type: integer
          example: 2
        status:
          type: string
          enum:
            - new
            - pending
            - accepted
            - rejected
          default: new
    Perevals:
      type: array
      items:
        $ref: "#/components/schemas/Pereval"
