# Generated by Django 4.2.2 on 2023-07-01 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerevalAdded",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date_added", models.DateTimeField()),
                ("raw_data", models.JSONField()),
                ("images", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "новый"),
                            ("pending", "ожидает_модерации"),
                            ("accepted", "принят"),
                            ("rejected", "отклонен"),
                        ],
                        default="new",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerevalAreas",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="PerevalImages",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "date_added",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 7, 1, 17, 43, 26, 562143, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("img", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="SprActivitiesTypes",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("title", models.TextField()),
            ],
        ),
    ]
