# Generated by Django 4.2.2 on 2023-07-01 18:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perevalimages",
            name="date_added",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 7, 1, 18, 17, 3, 468974, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
