# Generated by Django 4.2.2 on 2023-07-01 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_perevalareas_id_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coords",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("height", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("title", models.TextField(default="")),
                ("img", models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="perevaladded",
            name="images",
        ),
        migrations.RemoveField(
            model_name="perevaladded",
            name="raw_data",
        ),
        migrations.RemoveField(
            model_name="perevalimages",
            name="date_added",
        ),
        migrations.RemoveField(
            model_name="perevalimages",
            name="img",
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="add_first_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="beautyTitle",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="connect",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="level",
            field=models.TextField(
                choices=[
                    ("winter", ""),
                    ("summer", "1А"),
                    ("autumn", "1А"),
                    ("spring", ""),
                ],
                default="",
            ),
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="other_titles",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="title",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="perevalimages",
            name="pereval_id",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.perevaladded",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="perevaladded",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="perevalareas",
            name="title",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="spractivitiestypes",
            name="title",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="coord_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.coords"
            ),
        ),
        migrations.AddField(
            model_name="perevaladded",
            name="user_id",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.users"
            ),
        ),
        migrations.AddField(
            model_name="perevalimages",
            name="image_id",
            field=models.ForeignKey(
                default=0, on_delete=django.db.models.deletion.CASCADE, to="api.images"
            ),
            preserve_default=False,
        ),
    ]
